name: music_playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
