// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvQuJtSsOzgcZ7A2gVNMeKxoEhF2DBGM',
    appId: '1:609422563836:web:c8350b8c44b4474b1e3a79',
    messagingSenderId: '609422563836',
    projectId: 'adaptive-ui-c7b16',
    authDomain: 'adaptive-ui-c7b16.firebaseapp.com',
    storageBucket: 'adaptive-ui-c7b16.appspot.com',
    measurementId: 'G-7SPM14R08N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWESNOuxMvBPL0FUj-cvU1TK0g80js1yU',
    appId: '1:609422563836:android:a4d2b6fe2d52dc121e3a79',
    messagingSenderId: '609422563836',
    projectId: 'adaptive-ui-c7b16',
    storageBucket: 'adaptive-ui-c7b16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCArVP_bP1yyWcBlC5YCxPvgGcnn4Orf3E',
    appId: '1:609422563836:ios:1b7e1a1170be576d1e3a79',
    messagingSenderId: '609422563836',
    projectId: 'adaptive-ui-c7b16',
    storageBucket: 'adaptive-ui-c7b16.appspot.com',
    iosBundleId: 'gobindinho.com.musicPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCArVP_bP1yyWcBlC5YCxPvgGcnn4Orf3E',
    appId: '1:609422563836:ios:1b7e1a1170be576d1e3a79',
    messagingSenderId: '609422563836',
    projectId: 'adaptive-ui-c7b16',
    storageBucket: 'adaptive-ui-c7b16.appspot.com',
    iosBundleId: 'gobindinho.com.musicPlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvQuJtSsOzgcZ7A2gVNMeKxoEhF2DBGM',
    appId: '1:609422563836:web:7c2e36749e65a5f41e3a79',
    messagingSenderId: '609422563836',
    projectId: 'adaptive-ui-c7b16',
    authDomain: 'adaptive-ui-c7b16.firebaseapp.com',
    storageBucket: 'adaptive-ui-c7b16.appspot.com',
    measurementId: 'G-KRCE2WMNG7',
  );
}
